import { ChartBar, DownloadSimple, FileArrowUp, MagnifyingGlass, Receipt, TrendUp } from "@phosphor-icons/react";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { downloadFaturamento, fetchFaturamentoPreFatura, fetchFaturamentoSummary, importFaturamentoPreFatura, type FaturamentoSummary } from "./lib/api";

type Props = { token: string; currentUser: { name: string } | null };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);
const labels: Record<string, string> = { principal: "Rotas principais", "10pct": "10%", pnrs: "PNR's", perdidos: "Perdidos", pnrs_bugadas: "PNR's bugadas" };

export function FaturamentoScreen({ token }: Props) {
  const [type, setType] = useState("lastmile"); const [summary, setSummary] = useState<FaturamentoSummary | null>(null); const [selectedId, setSelectedId] = useState(""); const [baseReference, setBaseReference] = useState<File | null>(null); const [vehicleReference, setVehicleReference] = useState<File | null>(null);
  const [details, setDetails] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async (nextType = type) => { setLoading(true); setError(""); try { const result = await fetchFaturamentoSummary(token, nextType); setSummary(result); const id = result.selected?.id || ""; setSelectedId(id); if (id) setDetails(await fetchFaturamentoPreFatura(token, id)); else setDetails(null); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar faturamento."); } finally { setLoading(false); } };
  useEffect(() => { void load(type); }, [token, type]);
  useEffect(() => { if (!selectedId) return; const timer = window.setTimeout(() => { void fetchFaturamentoPreFatura(token, selectedId, search).then(setDetails).catch(() => undefined); }, 250); return () => window.clearTimeout(timer); }, [search, selectedId, token]);
  const maxBase = useMemo(() => Math.max(...(summary?.dashboard.byBase || []).map((item) => item.total), 1), [summary]);
  const handleUpload = async () => { if (!file) return; setLoading(true); setError(""); setMessage(""); try { const result = await importFaturamentoPreFatura(token, file, type, { base: baseReference || undefined, vehicle: vehicleReference || undefined }); setMessage(`${result.message} Pré-fatura #${result.numero} com ${result.totalLinhas} linhas.`); setFile(null); await load(type); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao importar arquivo."); } finally { setLoading(false); } };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null);
  return <main className="content-page faturamento-screen"><header className="page-heading"><div><p className="eyebrow">FATURAMENTO</p><h1>Faturamento</h1><p>Centralize pré-faturas por operação, acompanhe os indicadores e exporte os dados.</p></div></header>
    <section className="faturamento-toolbar"><div className="faturamento-operation"><span>Operação</span><strong>Mercado Livre</strong></div><label>Tipo de pré-fatura<select value={type} onChange={(e) => setType(e.target.value)}><option value="lastmile">LastMile</option><option value="linehaul">LineHaul</option><option value="melione">MeliOne</option></select></label><label className="faturamento-file"><FileArrowUp size={20} />{file ? file.name : "Escolher pré-fatura Excel"}<input type="file" accept=".xlsx,.xls" onChange={onFile} /></label><label className="faturamento-reference">Referência de bases<input type="file" accept=".xlsx,.xls" onChange={(e) => setBaseReference(e.target.files?.[0] || null)} /></label><label className="faturamento-reference">Referência de frotas<input type="file" accept=".xlsx,.xls" onChange={(e) => setVehicleReference(e.target.files?.[0] || null)} /></label><button className="primary-button" type="button" disabled={!file || loading} onClick={() => void handleUpload()}>Importar</button></section>
    {error ? <div className="inline-alert inline-alert--error">{error}</div> : null}{message ? <div className="inline-alert inline-alert--success">{message}</div> : null}
    {loading && !summary ? <section className="panel"><p className="loading-note">Carregando dados do faturamento...</p></section> : null}
    {summary ? <><section className="faturamento-kpis"><article><Receipt size={24} /><strong>{summary.selected ? `#${summary.selected.numero}` : "Nenhuma"}</strong><span>Última pré-fatura</span></article><article><TrendUp size={24} /><strong>{summary.dashboard.totalRoutes.toLocaleString("pt-BR")}</strong><span>Rotas identificadas</span></article><article><ChartBar size={24} /><strong>{money(summary.dashboard.totalGeneral)}</strong><span>Total das rotas</span></article><article><FileArrowUp size={24} /><strong>{summary.dashboard.totalRows.toLocaleString("pt-BR")}</strong><span>Linhas importadas</span></article></section>
      <section className="faturamento-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">VISÃO DA PRÉ-FATURA</p><h2>Valores por base</h2></div>{summary.selected ? <button className="secondary-button" type="button" onClick={() => void downloadFaturamento(token, summary.selected.id)}><DownloadSimple size={18} /> Exportar Excel</button> : null}</div>{summary.dashboard.byBase.length ? summary.dashboard.byBase.map((base) => <div className="faturamento-bar" key={base.sigla}><div><strong>{base.nomeBase}</strong><span>{base.linhas} linhas · {money(base.total)}</span></div><i style={{ width: `${Math.max(3, (base.total / maxBase) * 100)}%` }} /></div>) : <p className="empty-state">Importe uma pré-fatura para visualizar os indicadores.</p>}</div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">CATEGORIAS</p><h2>Distribuição</h2></div></div>{Object.entries(summary.dashboard.byCategory).map(([category, total]) => <div className="faturamento-category" key={category}><span>{labels[category] || category}</span><strong>{money(total)}</strong></div>)}</div></section>
      <section className="panel faturamento-history"><div className="panel-heading"><div><p className="eyebrow">HISTÓRICO</p><h2>Pré-faturas anteriores</h2></div></div><div className="faturamento-history-list">{summary.preFaturas.filter((item) => item.tipo === type).map((item) => <button className={item.id === selectedId ? "is-selected" : ""} key={item.id} type="button" onClick={() => { setSelectedId(item.id); void fetchFaturamentoPreFatura(token, item.id).then(setDetails); }}><strong>#{item.numero} · {item.nome_arquivo}</strong><span>{new Date(item.criado_em).toLocaleString("pt-BR")} · {item.total_linhas} linhas</span></button>)}</div></section>
      {details ? <section className="panel"><div className="panel-heading"><div><p className="eyebrow">DADOS</p><h2>Linhas da pré-fatura #{details.preFatura.numero}</h2></div><label className="faturamento-search"><MagnifyingGlass size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar motorista, placa ou base" /></label></div><div className="table-scroll"><table><thead><tr><th>Aba</th><th>Base</th><th>Motorista</th><th>Placa</th><th>ID da rota</th><th>Total</th></tr></thead><tbody>{details.items.map((item: any) => <tr key={item.id}><td>{item.aba}</td><td>{item.nome_base || item.sigla_base || "Não informado"}</td><td>{item.motorista || "Não informado"}</td><td>{item.placa || "Não informado"}</td><td>{item.id_rota || "-"}</td><td>{money(Number(item.total))}</td></tr>)}</tbody></table></div></section> : null}</> : null}</main>;
}
