import { Ambulance, CalendarBlank, ChartBar, ClockCounterClockwise, DownloadSimple, FileArrowUp, FileText, MagnifyingGlass, Receipt, TrendUp } from "@phosphor-icons/react";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import html2canvas from "html2canvas";
import { downloadFaturamento, fetchFaturamentoPreFatura, fetchFaturamentoSummary, importFaturamentoPreFatura, type FaturamentoSummary } from "./lib/api";

type Props = { token: string; currentUser: { name: string } | null };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);
const repairEncoding = (value: unknown) => String(value ?? "").replace(/Ã¡/g, "á").replace(/Ã©/g, "é").replace(/Ã­/g, "í").replace(/Ã³/g, "ó").replace(/Ãº/g, "ú").replace(/Ã£/g, "ã").replace(/Ãµ/g, "õ").replace(/Ã§/g, "ç").replace(/Ã‰/g, "É").replace(/Ãš/g, "Ú").replace(/Ã‚/g, "Â").replace(/Â/g, "");
const labels: Record<string, string> = { principal: "Rotas principais", "10pct": "Desconto 10%", pnrs: "Desconto PNR", perdidos: "Pacotes perdidos", pnrs_bugadas: "PNR's sem dados" };
const fortnight = (name: string) => { const month = name.match(/JANEIRO|FEVEREIRO|MAR[CÇ]O|ABRIL|MAIO|JUNHO|JULHO|AGOSTO|SETEMBRO|OUTUBRO|NOVEMBRO|DEZEMBRO/i)?.[0]?.toLowerCase(); return /1\s*Q|1A?\s*QUINZENA/i.test(name) ? `1ª quinzena${month ? ` de ${month}` : ""}` : /2\s*Q|2A?\s*QUINZENA/i.test(name) ? `2ª quinzena${month ? ` de ${month}` : ""}` : "Quinzena não identificada"; };

export function FaturamentoScreen({ token }: Props) {
  const [type, setType] = useState("lastmile"); const [summary, setSummary] = useState<FaturamentoSummary | null>(null); const [selectedId, setSelectedId] = useState(""); const [baseReference, setBaseReference] = useState<File | null>(null); const [vehicleReference, setVehicleReference] = useState<File | null>(null); const [historyOpen, setHistoryOpen] = useState(false); const [historySearch, setHistorySearch] = useState(""); const [historyType, setHistoryType] = useState("todos"); const [historyDate, setHistoryDate] = useState("");
  const [details, setDetails] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [exportingImage, setExportingImage] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async (nextType = type) => { setLoading(true); setError(""); try { const result = await fetchFaturamentoSummary(token, nextType); setSummary(result); const id = result.selected?.id || ""; setSelectedId(id); if (id) setDetails(await fetchFaturamentoPreFatura(token, id)); else setDetails(null); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar faturamento."); } finally { setLoading(false); } };
  useEffect(() => { void load(type); }, [token, type]);
  useEffect(() => { if (!selectedId) return; const timer = window.setTimeout(() => { void fetchFaturamentoPreFatura(token, selectedId, search).then(setDetails).catch(() => undefined); }, 250); return () => window.clearTimeout(timer); }, [search, selectedId, token]);
  const maxBase = useMemo(() => Math.max(...(summary?.dashboard.byBase || []).map((item) => item.total), 1), [summary]);
  const filteredHistory = useMemo(() => (summary?.preFaturas || []).filter((item) => {
    const matchesText = !historySearch || `${item.numero} ${item.nome_arquivo}`.toLowerCase().includes(historySearch.toLowerCase());
    const matchesType = historyType === "todos" || item.tipo === historyType;
    const matchesDate = !historyDate || String(item.criado_em).slice(0, 10) === historyDate;
    return matchesText && matchesType && matchesDate;
  }), [historyDate, historySearch, historyType, summary]);
  const handleUpload = async () => { if (!file) return; setLoading(true); setError(""); setMessage(""); try { const result = await importFaturamentoPreFatura(token, file, type, { base: baseReference || undefined, vehicle: vehicleReference || undefined }); setMessage(`${result.message} Pré-fatura #${result.numero} processada com sucesso.`); setFile(null); await load(type); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao importar arquivo."); } finally { setLoading(false); } };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null);
  const handleExportImage = async () => { const target = document.querySelector<HTMLElement>(".faturamento-screen"); if (!target || exportingImage) return; setExportingImage(true); setError(""); try { const canvas = await html2canvas(target, { backgroundColor: getComputedStyle(document.body).backgroundColor || "#f4f6fa", scale: Math.min(window.devicePixelRatio || 1, 2), useCORS: true, logging: false }); const link = document.createElement("a"); const numero = summary?.selected?.numero || "pre-fatura"; link.download = `visao-pre-fatura-${numero}.png`; link.href = canvas.toDataURL("image/png"); link.click(); } catch { setError("Não foi possível gerar a imagem da pré-fatura."); } finally { setExportingImage(false); } };
  return <main className="content-page faturamento-screen"><header className="page-heading faturamento-heading"><div><p className="eyebrow">FATURAMENTO / MERCADO LIVRE</p><div className="faturamento-title"><h1>Mercado Livre</h1><img className="mercado-livre-brand" src="/mercado-libre.svg" alt="Logo Mercado Livre" /></div><p>Pré-faturas, descontos, veículos e rotas em uma visão operacional completa.</p></div></header>
    <section className="faturamento-toolbar"><div className="faturamento-toolbar-options"><div className="faturamento-operation"><span>Operação</span><strong>Mercado Livre</strong>{summary?.selected ? <small>#{summary.selected.numero} · {summary.selected.tipo === "lastmile" ? "LastMile" : summary.selected.tipo === "linehaul" ? "LineHaul" : "MeliOne"} · {summary.selected.resumo?.quinzena || fortnight(summary.selected.nome_arquivo)}</small> : <small>Nenhuma pré-fatura selecionada</small>}</div><label>Tipo de pré-fatura<select value={type} onChange={(e) => setType(e.target.value)}><option value="lastmile">LastMile</option><option value="linehaul">LineHaul</option><option value="melione">MeliOne</option></select></label><details className="faturamento-references"><summary>Referências salvas</summary><div><label>Atualizar bases e siglas<input type="file" accept=".xlsx,.xls" onChange={(e) => setBaseReference(e.target.files?.[0] || null)} /></label><label>Atualizar veículos e frotas<input type="file" accept=".xlsx,.xls" onChange={(e) => setVehicleReference(e.target.files?.[0] || null)} /></label></div></details><button className="secondary-button faturamento-history-button" type="button" onClick={() => setHistoryOpen(true)}><ClockCounterClockwise size={18} /> Histórico</button></div><div className="faturamento-toolbar-upload"><label className="faturamento-file"><FileArrowUp size={20} /><span>{file ? file.name : summary?.selected?.nome_arquivo || "Selecionar pré-fatura Excel"}</span><input type="file" accept=".xlsx,.xls" onChange={onFile} /></label><button className="primary-button" type="button" disabled={!file || loading} onClick={() => void handleUpload()}>Importar pré-fatura</button></div></section>
    {error ? <div className="inline-alert inline-alert--error">{error}</div> : null}{message ? <div className="inline-alert inline-alert--success">{message}</div> : null}
    {loading && !summary ? <section className="panel"><p className="loading-note">Carregando dados do faturamento...</p></section> : null}
    {summary ? <><section className="faturamento-kpis"><article><Receipt size={24} /><strong>{summary.selected ? `#${summary.selected.numero}` : "Nenhuma"}</strong><span>Última pré-fatura</span></article><article><TrendUp size={24} /><strong>{summary.dashboard.totalRoutes.toLocaleString("pt-BR")}</strong><span>Rotas únicas</span></article><article><ChartBar size={24} /><strong>{money(summary.dashboard.totalGeneral)}</strong><span>Valor das rotas principais</span></article><article><FileArrowUp size={24} /><strong>{(summary.dashboard.totalVehicles || 0).toLocaleString("pt-BR")}</strong><span>Veículos únicos</span></article><article><Ambulance size={24} /><strong>{(summary.dashboard.totalAmbulances || 0).toLocaleString("pt-BR")}</strong><span>Ambulâncias</span></article><article><FileText size={24} /><strong>{(summary.dashboard.totalPnrs || 0).toLocaleString("pt-BR")}</strong><span>PNR</span></article><article><ChartBar size={24} /><strong>{money(summary.dashboard.byCategory.perdidos || 0)}</strong><span>Pacotes perdidos</span></article><article><ChartBar size={24} /><strong>{money((summary.dashboard.byCategory.pnrs || 0) + (summary.dashboard.byCategory.pnrs_bugadas || 0))}</strong><span>Desconto PNR total</span></article><article><ChartBar size={24} /><strong>{money(summary.dashboard.byCategory["10pct"] || 0)}</strong><span>Desconto 10%</span></article><article><CalendarBlank size={24} /><strong>{(summary.dashboard.weekendRoutes || 0).toLocaleString("pt-BR")}</strong><span>Rotas no fim de semana</span></article></section>
      <section className="faturamento-grid faturamento-grid--overview"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">VISÃO DA PRÉ-FATURA</p><h2>Ranking de faturamento por base</h2><p className="panel-subtitle">Compare o peso financeiro de cada base em uma leitura horizontal.</p></div><div className="faturamento-chart-actions">{summary.selected ? <button className="secondary-button faturamento-export-image-button" type="button" disabled={exportingImage} onClick={() => void handleExportImage()}><DownloadSimple size={18} /> {exportingImage ? "Gerando imagem..." : "Exportar"}</button> : null}</div></div>{summary.dashboard.byBase.length ? <div className="faturamento-bars-viewport"><div className="faturamento-bars-chart">{summary.dashboard.byBase.map((base, index) => <article className="faturamento-bar-row" key={base.sigla}><div className="faturamento-bar-label"><b>{String(index + 1).padStart(2, "0")}</b><strong title={base.nomeBase}>{base.nomeBase}</strong><small>{base.sigla} · {base.rotas} rotas · {base.veiculos} veículos</small></div><div className="faturamento-bar-track"><span style={{ width: `${Math.max(3, (base.total / maxBase) * 100)}%` }} /><strong>{money(base.total)}</strong></div></article>)}</div></div> : <p className="empty-state">Importe uma pré-fatura para visualizar os indicadores.</p>}</div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">QUALIDADE DOS DADOS</p><h2>Conferência</h2></div></div><div className="faturamento-quality"><strong>{summary.dashboard.missingBaseRows}</strong><span>rotas sem sigla/base na pré-fatura</span></div><div className="faturamento-quality"><strong>{summary.dashboard.siglaOnlyRows}</strong><span>rotas com sigla sem nome na pré-fatura</span></div>{Object.entries(summary.dashboard.byCategory).map(([category, total]) => <div className="faturamento-category" key={category}><span>{labels[category] || category}</span><strong>{money(total)}</strong></div>)}<div className="faturamento-insight"><strong>Leitura operacional</strong><span>Rotas sem sigla/base devem ser corrigidas antes de consolidar divergências financeiras.</span></div></div></section>
      <section className="faturamento-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">EVOLUÇÃO OPERACIONAL</p><h2>Veículos por modalidade</h2></div></div><div className="faturamento-modal-grid">{summary.dashboard.byModal.map((modal, index) => <article className="faturamento-modal" key={modal.modal}><div className="faturamento-modal-heading"><b>{String(index + 1).padStart(2, "0")}</b><strong>{repairEncoding(modal.modal)}</strong></div><span>{modal.veiculos} veículos · {modal.rotas} rotas</span><strong className="faturamento-modal-total">{money(modal.total)}</strong><i style={{ width: `${Math.max(5, (modal.total / Math.max(...summary.dashboard.byModal.map((item) => item.total), 1)) * 100)}%` }} /></article>)}</div></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">AMBULÂNCIAS</p><h2>Ambulâncias pagas na pré-fatura</h2></div></div>{summary.dashboard.ambulancesByBase.length ? summary.dashboard.ambulancesByBase.map((item) => <div className="faturamento-category" key={item.base}><span>{repairEncoding(item.base)}<small>{item.solicitacoes} ocorrências de ambulância</small></span><strong>{item.rotas} rotas</strong></div>) : <p className="empty-state">Nenhuma ambulância identificada nesta pré-fatura.</p>}</div></section>
      {details ? <section className="panel faturamento-data"><div className="panel-heading"><div><p className="eyebrow">DADOS DA PRÉ-FATURA</p><h2>Detalhes de #{details.preFatura.numero}</h2><p className="panel-subtitle">Aba, base, veículo, rota e valores persistidos no banco.</p></div><label className="faturamento-search"><MagnifyingGlass size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar motorista, placa ou base" /></label></div><div className="table-scroll"><table><thead><tr><th>Categoria</th><th>Base</th><th>Veículo</th><th>Motorista</th><th>Placa</th><th>ID da rota</th><th>Quantidade</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{details.items.map((item: any) => <tr key={item.id}><td>{labels[item.categoria] || item.categoria}</td><td>{item.nome_base || item.sigla_base || "Não informado"}</td><td>{item.veiculo_modal || "Não informado"}</td><td>{item.motorista || "Não informado"}</td><td>{item.placa || "Não informado"}</td><td>{item.id_rota || "-"}</td><td>{item.quantidade ?? "-"}</td><td>{money(Number(item.preco_unitario))}</td><td>{money(Number(item.total))}</td></tr>)}</tbody></table></div></section> : null}</> : null}
      {historyOpen ? <div className="modal-overlay" onClick={() => setHistoryOpen(false)}><div className="modal-card faturamento-history-modal" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">HISTÓRICO DE IMPORTAÇÕES</p><h2>Pesquisar pré-fatura</h2></div><button className="ghost-button" type="button" onClick={() => setHistoryOpen(false)}>Fechar</button></div><div className="faturamento-history-filters"><input value={historySearch} onChange={(e) => setHistorySearch(e.target.value)} placeholder="Número ou nome do arquivo" /><select value={historyType} onChange={(e) => setHistoryType(e.target.value)}><option value="todos">Todos os tipos</option><option value="lastmile">LastMile</option><option value="linehaul">LineHaul</option><option value="melione">MeliOne</option></select><input type="date" value={historyDate} onChange={(e) => setHistoryDate(e.target.value)} /></div><div className="faturamento-history-list">{filteredHistory.map((item) => <button key={item.id} type="button" onClick={() => { setType(item.tipo); setSelectedId(item.id); setHistoryOpen(false); void fetchFaturamentoPreFatura(token, item.id).then(setDetails); }}><strong>#{item.numero} · {item.tipo}</strong><span>{new Date(item.criado_em).toLocaleString("pt-BR")} · {Number(item.total_rotas || 0).toLocaleString("pt-BR")} rotas</span></button>)}</div></div></div> : null}</main>;
}
