import { ChartBar, DownloadSimple, FileArrowUp, MagnifyingGlass, Receipt, TrendUp } from "@phosphor-icons/react";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { downloadFaturamento, fetchFaturamentoPreFatura, fetchFaturamentoSummary, importFaturamentoPreFatura, type FaturamentoSummary } from "./lib/api";

type Props = { token: string; currentUser: { name: string } | null };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);
const labels: Record<string, string> = { principal: "Rotas principais", "10pct": "10%", pnrs: "PNR's", perdidos: "Perdidos", pnrs_bugadas: "PNR's bugadas" };
const fortnight = (name: string) => /1\s*Q|1A?\s*QUINZENA/i.test(name) ? "1ª quinzena" : /2\s*Q|2A?\s*QUINZENA/i.test(name) ? "2ª quinzena" : "Quinzena não identificada";

export function FaturamentoScreen({ token }: Props) {
  const [type, setType] = useState("lastmile"); const [summary, setSummary] = useState<FaturamentoSummary | null>(null); const [selectedId, setSelectedId] = useState(""); const [baseReference, setBaseReference] = useState<File | null>(null); const [vehicleReference, setVehicleReference] = useState<File | null>(null); const [historyOpen, setHistoryOpen] = useState(false); const [historySearch, setHistorySearch] = useState(""); const [historyType, setHistoryType] = useState("todos"); const [historyDate, setHistoryDate] = useState("");
  const [details, setDetails] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async (nextType = type) => { setLoading(true); setError(""); try { const result = await fetchFaturamentoSummary(token, nextType); setSummary(result); const id = result.selected?.id || ""; setSelectedId(id); if (id) setDetails(await fetchFaturamentoPreFatura(token, id)); else setDetails(null); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar faturamento."); } finally { setLoading(false); } };
  useEffect(() => { void load(type); }, [token, type]);
  useEffect(() => { if (!selectedId) return; const timer = window.setTimeout(() => { void fetchFaturamentoPreFatura(token, selectedId, search).then(setDetails).catch(() => undefined); }, 250); return () => window.clearTimeout(timer); }, [search, selectedId, token]);
  const maxBase = useMemo(() => Math.max(...(summary?.dashboard.byBase || []).map((item) => item.total), 1), [summary]);
  const filteredHistory = useMemo(() => (summary?.preFaturas || []).filter((item) => {
    const matchesText = !historySearch || `${item.numero} ${item.nome_arquivo}`.toLowerCase().includes(historySearch.toLowerCase());
    const matchesType = historyType === "todos" || item.tipo === historyType;
    const matchesDate = !historyDate || String(item.criado_em).slice(0, 10) === historyDate;
    return matchesText && matchesType && matchesDate;
  }), [historyDate, historySearch, historyType, summary]);
  const handleUpload = async () => { if (!file) return; setLoading(true); setError(""); setMessage(""); try { const result = await importFaturamentoPreFatura(token, file, type, { base: baseReference || undefined, vehicle: vehicleReference || undefined }); setMessage(`${result.message} Pré-fatura #${result.numero} com ${result.totalLinhas} linhas.`); setFile(null); await load(type); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao importar arquivo."); } finally { setLoading(false); } };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null);
  return <main className="content-page faturamento-screen"><header className="page-heading"><div><p className="eyebrow">FATURAMENTO / MERCADO LIVRE</p><h1>Mercado Livre</h1><p>Pré-faturas, descontos, veículos e rotas em uma visão operacional completa.</p></div></header>
    {summary ? <section className="faturamento-history faturamento-history--top"><div className="panel-heading"><div><p className="eyebrow">PRÉ-FATURA SELECIONADA</p><h2>{summary.selected ? `#${summary.selected.numero} · ${summary.selected.tipo === "lastmile" ? "LastMile" : summary.selected.tipo === "linehaul" ? "LineHaul" : "MeliOne"} · ${summary.selected.resumo?.quinzena || fortnight(summary.selected.nome_arquivo)}` : "Nenhuma pré-fatura"}</h2><p className="faturamento-history-hint">{summary.selected ? `${summary.selected.nome_arquivo} · importada em ${new Date(summary.selected.criado_em).toLocaleDateString("pt-BR")}` : "Importe uma pré-fatura para começar."}</p></div><button className="secondary-button" type="button" onClick={() => setHistoryOpen(true)}>Navegar pelo histórico</button></div></section> : null}
    <section className="faturamento-toolbar"><div className="faturamento-operation"><span>Operação</span><strong>Mercado Livre</strong></div><label>Tipo de pré-fatura<select value={type} onChange={(e) => setType(e.target.value)}><option value="lastmile">LastMile</option><option value="linehaul">LineHaul</option><option value="melione">MeliOne</option></select></label><label className="faturamento-file"><FileArrowUp size={20} />{file ? file.name : "Escolher pré-fatura Excel"}<input type="file" accept=".xlsx,.xls" onChange={onFile} /></label><details className="faturamento-references"><summary>Referências salvas</summary><div><label>Atualizar bases e siglas<input type="file" accept=".xlsx,.xls" onChange={(e) => setBaseReference(e.target.files?.[0] || null)} /></label><label>Atualizar veículos e frotas<input type="file" accept=".xlsx,.xls" onChange={(e) => setVehicleReference(e.target.files?.[0] || null)} /></label></div></details><button className="primary-button" type="button" disabled={!file || loading} onClick={() => void handleUpload()}>Importar pré-fatura</button></section>
    {error ? <div className="inline-alert inline-alert--error">{error}</div> : null}{message ? <div className="inline-alert inline-alert--success">{message}</div> : null}
    {loading && !summary ? <section className="panel"><p className="loading-note">Carregando dados do faturamento...</p></section> : null}
    {summary ? <><section className="faturamento-kpis"><article><Receipt size={24} /><strong>{summary.selected ? `#${summary.selected.numero}` : "Nenhuma"}</strong><span>Última pré-fatura</span></article><article><TrendUp size={24} /><strong>{summary.dashboard.totalRoutes.toLocaleString("pt-BR")}</strong><span>Rotas identificadas</span></article><article><ChartBar size={24} /><strong>{money(summary.dashboard.totalGeneral)}</strong><span>Total das rotas</span></article><article><FileArrowUp size={24} /><strong>{summary.dashboard.totalRows.toLocaleString("pt-BR")}</strong><span>Linhas importadas</span></article></section>
      <section className="faturamento-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">VISÃO DA PRÉ-FATURA</p><h2>Valores e impacto por base</h2></div>{summary.selected ? <button className="secondary-button" type="button" onClick={() => void downloadFaturamento(token, summary.selected.id)}><DownloadSimple size={18} /> Exportar Excel</button> : null}</div>{summary.dashboard.byBase.length ? summary.dashboard.byBase.map((base) => <div className="faturamento-bar" key={base.sigla}><div><strong>{base.nomeBase} <small>({base.sigla})</small></strong><span>{base.linhas} linhas · {base.veiculos} veículos · {money(base.total)}</span></div><i style={{ width: `${Math.max(3, (base.total / maxBase) * 100)}%` }} /><small className="faturamento-discount">Descontos e ocorrências: {money(base.descontos)}</small></div>) : <p className="empty-state">Importe uma pré-fatura para visualizar os indicadores.</p>}</div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">QUALIDADE DOS DADOS</p><h2>Conferência</h2></div></div><div className="faturamento-quality"><strong>{summary.dashboard.missingBaseRows}</strong><span>linhas sem base identificada</span></div><div className="faturamento-quality"><strong>{summary.dashboard.siglaOnlyRows}</strong><span>linhas exibidas apenas com sigla</span></div>{Object.entries(summary.dashboard.byCategory).map(([category, total]) => <div className="faturamento-category" key={category}><span>{labels[category] || category}</span><strong>{money(total)}</strong></div>)}<div className="faturamento-insight"><strong>Leitura operacional</strong><span>Registros sem base devem ser corrigidos antes de consolidar divergências financeiras.</span></div></div></section>
      <section className="faturamento-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">EVOLUÇÃO OPERACIONAL</p><h2>Modalidades e veículos</h2></div></div>{summary.dashboard.byModal.slice(0, 12).map((modal) => <div className="faturamento-modal" key={modal.modal}><div><strong>{modal.modal}</strong><span>{modal.rotas} rotas · {modal.linhas} linhas · {money(modal.total)}</span></div><i style={{ width: `${Math.max(3, (modal.total / Math.max(...summary.dashboard.byModal.map((item) => item.total), 1)) * 100)}%` }} /></div>)}</div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">AMBULÂNCIAS</p><h2>Solicitações por base</h2></div></div>{summary.dashboard.ambulancesByBase.length ? summary.dashboard.ambulancesByBase.map((item) => <div className="faturamento-category" key={item.base}><span>{item.base}<small>{item.rotas} rotas</small></span><strong>{item.solicitacoes}</strong></div>) : <p className="empty-state">Nenhuma ambulância identificada.</p>}</div></section>
      {details ? <section className="panel faturamento-data"><div className="panel-heading"><div><p className="eyebrow">DADOS DA PRÉ-FATURA</p><h2>Linhas de #{details.preFatura.numero}</h2><p className="panel-subtitle">Aba, base, veículo, rota e valores persistidos no banco.</p></div><label className="faturamento-search"><MagnifyingGlass size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar motorista, placa ou base" /></label></div><div className="table-scroll"><table><thead><tr><th>Categoria</th><th>Base</th><th>Veículo</th><th>Motorista</th><th>Placa</th><th>ID da rota</th><th>Quantidade</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{details.items.map((item: any) => <tr key={item.id}><td>{labels[item.categoria] || item.categoria}</td><td>{item.nome_base || item.sigla_base || "Não informado"}</td><td>{item.veiculo_modal || "Não informado"}</td><td>{item.motorista || "Não informado"}</td><td>{item.placa || "Não informado"}</td><td>{item.id_rota || "-"}</td><td>{item.quantidade ?? "-"}</td><td>{money(Number(item.preco_unitario))}</td><td>{money(Number(item.total))}</td></tr>)}</tbody></table></div></section> : null}</> : null}
      {historyOpen ? <div className="modal-overlay" onClick={() => setHistoryOpen(false)}><div className="modal-card faturamento-history-modal" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">HISTÓRICO DE IMPORTAÇÕES</p><h2>Pesquisar pré-fatura</h2></div><button className="ghost-button" type="button" onClick={() => setHistoryOpen(false)}>Fechar</button></div><div className="faturamento-history-filters"><input value={historySearch} onChange={(e) => setHistorySearch(e.target.value)} placeholder="Número ou nome do arquivo" /><select value={historyType} onChange={(e) => setHistoryType(e.target.value)}><option value="todos">Todos os tipos</option><option value="lastmile">LastMile</option><option value="linehaul">LineHaul</option><option value="melione">MeliOne</option></select><input type="date" value={historyDate} onChange={(e) => setHistoryDate(e.target.value)} /></div><div className="faturamento-history-list">{filteredHistory.map((item) => <button key={item.id} type="button" onClick={() => { setType(item.tipo); setSelectedId(item.id); setHistoryOpen(false); void fetchFaturamentoPreFatura(token, item.id).then(setDetails); }}><strong>#{item.numero} · {item.tipo}</strong><span>{new Date(item.criado_em).toLocaleString("pt-BR")} · {item.total_linhas.toLocaleString("pt-BR")} linhas</span></button>)}</div></div></div> : null}</main>;
}
